name: CI Production
on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 'v14.2.0'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout eks-ms-app
        uses: actions/checkout@v2
        with:
          path: app
      - name: Build and Push the Image
        run: |
          cd ./app/microservice-one
          npm i
          TIMESTAMP=$(date +%s)
          docker build . -t ghcr.io/${{ github.actor }}/${{ github.repository }}-production:tmstp-$TIMESTAMP
          docker push ghcr.io/dinoradulovic/k8s-microservices-app-production:tmstp-$TIMESTAMP
